---
- name: configuring desktop system
  hosts: localhost
  become: no
  pre_tasks:
    - name: set variables - include all .yaml files in config/shared directory
      include_vars:
        dir: ../config/shared
        extensions:
          - "yaml"
    - name: set variables - include all .yaml files in config/tower directory
      include_vars:
        dir: ../config/poptop
        extensions:
          - "yaml"
    - name: update repositories
      become: true
      apt: update_cache=yes
    - import_tasks: ../pkgs/dependencies.yaml
  tasks:
    - import_tasks: tasks/desktop/software/init.yaml
    - import_tasks: tasks/dev/init.yaml
    - import_tasks: tasks/cloud/init.yaml
    - import_tasks: tasks/system/init.yaml
    - import_tasks: tasks/desktop/software/tower-software.yaml
    - import_tasks: tasks/desktop/popos.yaml
  # roles:
  # - zsh
  post_tasks:
    - name: updating the system
      become: true
      apt:
        update_cache: yes
        upgrade: dist
    - name: autoremove and purge apt packages
      become: true
      apt:
        autoremove: yes
        purge: yes
    - import_tasks: tasks/final-message.yaml
