---
# Maintenance playbook - updates, cleanup, etc.
- name: System Maintenance
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true
      when: updates.auto_update | default(false)

    - name: Update flatpak packages
      ansible.builtin.command: flatpak update -y
      changed_when: false
      failed_when: false

    - name: Update snap packages
      ansible.builtin.command: snap refresh
      changed_when: false
      failed_when: false

    - name: Clean up old kernels
      ansible.builtin.shell: |
        apt autoremove --purge -y
      changed_when: false

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Rebooting to apply updates"
        reboot_timeout: 300
      when:
        - reboot_required.stat.exists
        - updates.auto_reboot | default(false)
