roles:
  # from galaxy
  # - name: hurricanehrndz.rustup

  # Personal roles on GitHub
  # - src: https://github.com/bashfulrobot/scrape-module.git
  #   scm: git
  #   version: main
# You can also add collections
collections:
  - name: community.general
