---
# Main playbook - runs all configuration
- name: Configure Desktop Systems
  hosts: all
  become: true

  roles:
  # Bootstrap role - only run with --tags bootstrap (never runs by default)
    - role: bootstrap
      tags: [bootstrap, never]

    # Core system configuration
    - role: system
      tags: [system, core]

    # Desktop environment configuration
    - role: desktop
      tags: [cosmic, core]

    # User applications
    - role: apps
      tags: [apps]

    # Kubernetes tools and services
    - role: k8s
      tags: [k8s, kubernetes, infrastructure]

    # Custom desktop launchers
    - role: custom_launchers
      when: inventory_hostname == 'qbert'
      tags: [custom_launchers, apps]
