---
# Visual Studio Code installation via official Microsoft repository

- name: Install dependencies for VSCode
  apt:
    name:
      - wget
      - gpg
      - apt-transport-https
    state: present
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Remove conflicting VSCode repository files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/vscode.list
    - /etc/apt/sources.list.d/vscode.sources
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Remove conflicting Microsoft GPG keys
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/share/keyrings/microsoft.gpg
    - /etc/apt/trusted.gpg.d/microsoft.gpg
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Download Microsoft GPG key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: '0644'
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Add Microsoft GPG key to keyrings
  shell: |
    gpg --dearmor < /tmp/microsoft.asc > /usr/share/keyrings/packages.microsoft.gpg
    chmod 644 /usr/share/keyrings/packages.microsoft.gpg
  args:
    creates: /usr/share/keyrings/packages.microsoft.gpg
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Clean up temporary GPG key file
  file:
    path: /tmp/microsoft.asc
    state: absent
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Add VSCode repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Flush handlers to ensure apt cache is updated
  meta: flush_handlers

- name: Install Visual Studio Code
  apt:
    name: code
    state: "{{ app_states['vscode'] | default('present') }}"
    update_cache: yes
  become: yes

# Cleanup when absent
- name: Remove VSCode repository when absent
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: absent
  become: yes
  when: app_states['vscode'] | default('present') == 'absent'

- name: Remove Microsoft GPG key when absent
  file:
    path: /usr/share/keyrings/packages.microsoft.gpg
    state: absent
  become: yes
  when: app_states['vscode'] | default('present') == 'absent'
