---
# Visual Studio Code installation via official Microsoft repository

- name: Install dependencies for VSCode
  apt:
    name:
      - wget
      - gpg
      - apt-transport-https
    state: present
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Add Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/packages.microsoft.gpg
    state: present
  become: yes
  when: app_states['vscode'] | default('present') == 'present'

- name: Add VSCode repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present
  become: yes
  when: app_states['vscode'] | default('present') == 'present'
  notify: Update apt cache

- name: Flush handlers to ensure apt cache is updated
  meta: flush_handlers

- name: Install Visual Studio Code
  apt:
    name: code
    state: "{{ app_states['vscode'] | default('present') }}"
    update_cache: yes
  become: yes

# Cleanup when absent
- name: Remove VSCode repository when absent
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: absent
  become: yes
  when: app_states['vscode'] | default('present') == 'absent'

- name: Remove Microsoft GPG key when absent
  file:
    path: /usr/share/keyrings/packages.microsoft.gpg
    state: absent
  become: yes
  when: app_states['vscode'] | default('present') == 'absent'
