- name: Installing Blackbox - pkgs/blackbox.yaml
  community.general.flatpak:
    name:
      - com.raggesilver.BlackBox
    state: present
    method: user
    remote: flathub

- name: Placing blackbox launcher - pkgs/blackbox.yaml
  become: true
  ansible.builtin.copy:
    src: files/usr/local/bin/blackbox
    dest: "/usr/local/bin/blackbox"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - cfg

- name: Add blackbox to alternatives - pkgs/blackbox.yaml
  become: true
  community.general.alternatives:
    name: x-terminal-emulator
    path: /usr/local/bin/blackbox
    link: /usr/bin/x-terminal-emulator
    priority: "10"
  tags:
    - cfg

- name: Set blackbox as the default terminal - pkgs/blackbox.yaml
  become: true
  community.general.alternatives:
    name: x-terminal-emulator
    path: /usr/local/bin/blackbox
  tags:
    - cfg
