---
- name: Set apt gpg key - pkgs/chrome.yaml
  become: true
  ansible.builtin.apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present
  tags:
    - init

- name: Add repository - pkgs/chrome.yaml
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome
    update_cache: true
  tags:
    - init

- name: Install - pkgs/chrome.yaml
  become: true
  ansible.builtin.apt:
    name: google-chrome-stable
  tags:
    - install
