---
# this file ensures baseline dependencies are met for the core of other tasks.
# i.e. tasks that install flatpaks would not work if flatpak was not installed
- name: Dependencies - add canonical partners ppa
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner
    state: present
  tags:
    - init
- name: Dependencies - installing dependencies via apt
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-pip # install pip packages
      - flatpak # install flatpaks
      - gnome-software-plugin-flatpak
    state: present
  tags:
    - init
- name: Dependencies - installing dependencies via pip
  become: true
  ansible.builtin.pip:
    name:
      - github3.py # for github latest releases
      - beautifulsoup4 # for web scraping
  tags:
    - init

- name: Dependencies - add the flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  tags:
    - init

- name: Dependencies - create ansible module folder
  ansible.builtin.file:
    path: "{{ SYSTEM_HOME }}/.ansible/modules/"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
  tags:
    - init

- name: Dependencies - create autostart folder
  ansible.builtin.file:
    path: "{{ SYSTEM_HOME }}/.config/autostart/"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
  tags:
    - init

- name: Dependencies - installing scrape.py andible module
  ansible.builtin.copy:
    src: ../files/home/.ansible/modules/scrape.py
    dest: "{{ SYSTEM_HOME }}/.ansible/modules/scrape.py"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
  tags:
    - init

- name: Dependencies - create ansible automation folder
  ansible.builtin.file:
    path: "{{ SYSTEM_HOME }}/.config/ansible-automation"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
  tags:
    - init
