- name: Installing flatpaks - pkgs/general.yaml
  community.general.flatpak:
    name:
      - md.obsidian.Obsidian
      - com.todoist.Todoist
      - org.telegram.desktop
      - com.obsproject.Studio
    state: present
    method: user
    remote: flathub

- name: Installing debs - pkgs/general.yaml
  become: true
  ansible.builtin.apt:
    pkg:
      - dconf-cli
      - xournal
      - restic
      - xclip
      - ncdu
      - ubuntu-restricted-extras
      - ubuntu-restricted-addons
      - gnome-disk-utility
      - gnome-firmware
      - dlocate
      - ttf-mscorefonts-installer
      - fonts-powerline
      - fonts-emojione
      - ppa-purge
      - gnome-calculator
      - dialog
      - stacer
      - gnupg-agent
      - font-manager
      - v4l-utils
      - nvme-cli
      - celluloid
      - zoxide
      - jq
      - whois
      - curl
      - wget
      - tmux
      # cargo dependency
      - pkg-config
    state: present

- name: removing debs - pkgs/general.yaml
  become: true
  ansible.builtin.apt:
    pkg:
      - firefox
    state: absent

- name: Install pip packages - pkgs/general.yaml
  ansible.builtin.pip:
    name:
      - ansible-lint
      - telegram-send
      # Needed for some ansible modules
      - psutil

- name: Create Applications folder - pkgs/general.yaml
  ansible.builtin.file:
    path: "{{ SYSTEM_HOME }}/Applications"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
  tags:
    - init
