---
# Signal Desktop installation via APT repository
# Private messaging application

- name: Add Signal APT repository with GPG key
  ansible.builtin.deb822_repository:
    name: signal-desktop
    types: [deb]
    uris: https://updates.signal.org/desktop/apt
    suites: xenial
    components: [main]
    signed_by: https://updates.signal.org/desktop/apt/keys.asc
    state: "{{ app_states['signal'] | default('present') }}"
  become: true

- name: Update APT cache after repository changes
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Signal Desktop
  ansible.builtin.apt:
    name: signal-desktop
    state: "{{ app_states['signal'] | default('present') }}"
    purge: "{{ app_states['signal'] | default('present') == 'absent' }}"
  become: true
