- name: dev/editor - install editor dependencies
  become: yes
  ansible.builtin.apt:
    pkg:
      - editorconfig
      - uncrustify
    state: present

- name: dev/editor - create default editorconfig folder
  file:
    path: "{{ SYSTEM_HOME }}/.config/editorconfig"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

- name: dev/editor - create uncrustify folder
  file:
    path: "{{ SYSTEM_HOME }}/.config/uncrustify"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

- name: dev/editor - installing .editorconfig default file
  copy:
    src: ../files/home/.config/editorconfig/.editorconfig
    dest: "{{ SYSTEM_HOME }}/.config/editorconfig/.editorconfig"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    mode: 0700

- name: dev/editor - installing uncrustify.cfg
  copy:
    src: ../files/home/.config/uncrustify/uncrustify.cfg
    dest: "{{ SYSTEM_HOME }}/.config/uncrustify/uncrustify.cfg"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    mode: 0700