---
- name: dev/git-config - install git
  become: yes
  ansible.builtin.apt:
    pkg:
      - git
    state: present

- name: dev/git-config - configure user email
  git_config:
    name: user.email
    scope: global
    value: "{{ MY_EMAIL }}"
- name: dev/git-config - configure name
  git_config:
    name: user.name
    scope: global
    value: "{{ MY_FULLNAME }}"
- name: dev/git-config - configure username
  git_config:
    name: user.username
    scope: global
    value: "{{ MY_GITHUB_USERNAME }}"
- name: dev/git-config - configure user signing key
  git_config:
    name: user.signingKey
    scope: global
    value: "{{ MY_GIT_SIGNKEY }}"
- name: dev/git-config - configure gpg signing
  git_config:
    name: commit.gpgsign
    scope: global
    value: "true"
- name: dev/git-config - set git config - editor
  git_config:
    name: core.editor
    scope: global
    value: "code-insiders --wait"
- name: dev/git-config - set git default branch
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"

- name: dev/git-config - get latest release version of gh cli from github
  github_release:
    user: cli
    repo: cli
    action: latest_release
    token: "{{ GITHUB_TOKEN }}"
  register: gh_cli_release

- name: dev/git-config - get gh cli version number w/o v
  set_fact:
    gh_cli_version: "{{ gh_cli_release.tag | regex_replace('^v', '') }}"

- name: dev/git-config - install gh cli .deb package from github
  become: yes
  apt:
    deb: https://github.com/cli/cli/releases/download/{{ gh_cli_release.tag }}/gh_{{ gh_cli_version }}_linux_amd64.deb