- name: dev/go - create golang package directory
  become: yes
  file:
    path: "{{GOLANG_PACKAGE_CACHE}}"
    state: directory
- name: dev/go - download golang
  become: yes
  get_url:
    url: "https://dl.google.com/go/go{{GOLANG_VERSION}}.linux-amd64.tar.gz"
    dest: "{{GOLANG_PACKAGE_CACHE}}/go{{GOLANG_VERSION}}.linux-amd64.tar.gz"
    # checksum: "{{golang_checksum}}"
- name: dev/go - install golang
  become: yes
  unarchive:
    src: "{{GOLANG_PACKAGE_CACHE}}/go{{GOLANG_VERSION}}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
    creates: /usr/local/bin/go
- name: dev/go - add goroot to global profile
  become: yes
  lineinfile:
    path: /etc/profile
    line: export goroot=/usr/local/go
- name: dev/go - add go to path in global profile
  become: yes
  lineinfile:
    path: /etc/profile
    line: export path=$path:/usr/local/bin/go
