- name: tasks/dev - get latest release version of gptcommit from github
  github_release:
    user: zurawiki
    repo: gptcommit
    action: latest_release
    token: "{{ GITHUB_TOKEN }}"
  register: gptcommit_release

# - name: tasks/dev - clean up gptcommit version number
#   set_fact:
#     gptcommit_version: "{{ gptcommit_release.tag | regex_replace('^v', '') }}"

- name: tasks/dev - download & extract gptcommit tar
  unarchive:
    src: "https://github.com/zurawiki/gptcommit/releases/download/{{ gptcommit_release.tag }}/gptcommit-x86_64-unknown-linux-gnu.tar.gz"
    dest: /tmp
    remote_src: yes

- name: tasks/dev - install gptcommit
  become: yes
  ansible.builtin.copy:
    src: /tmp/gptcommit
    dest: /usr/local/bin/gptcommit
    owner: "root"
    group: "root"
    mode: "0755"

- name: tasks/dev - configure gptcommit
  copy:
    src: ../files/home/.config/gptcommit/config.toml
    dest: "{{SYSTEM_HOME}}/.config/gptcommit/config.toml"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
