- name: dev/hugo - get latest release version
  github_release:
    user: gohugoio
    repo: hugo
    action: latest_release
    token: "{{ GITHUB_TOKEN }}"
  register: hugo_release

- name: dev/hugo - get hugo version number w/o v
  set_fact:
    hugo_version: "{{ hugo_release.tag | regex_replace('^v', '') }}"

- name: dev/hugo - install
  become: true
  apt:
    deb: https://github.com/gohugoio/hugo/releases/download/{{ hugo_release.tag }}/hugo_extended_{{ hugo_version }}_Linux-64bit.deb
