# - name: dev/shadowenv - get latest release version of shadowenv from github
#   github_release:
#     user: shopify
#     repo: shadowenv
#     action: latest_release
#     token: "{{ GITHUB_TOKEN }}"
#   register: shadowenv_release

# Had to see the format returned.
# JSON
# - debug: msg="{{ shadowenv_release.tag }}"

# - name: dev/shadowenv - download
#   become: yes
#   get_url:
#     url: "https://github.com/mvdan/sh/releases/download/{{ shadowenv_release.tag }}/shadowenv_{{ shadowenv_release.tag }}_linux_amd64"
#     dest: /usr/local/bin/shadowenv
#     mode: "0755"

- name: dev/shadowenv - download
  become: yes
  get_url:
    url: "https://github.com/Shopify/shadowenv/releases/download/2.0.7/shadowenv-x86_64-unknown-linux-gnu"
    dest: /usr/local/bin/shadowenv
    mode: "0755"
