- name: dev/shfmt - get latest release version of shfmt from github
  github_release:
    user: mvdan
    repo: sh
    action: latest_release
    token: "{{ GITHUB_TOKEN }}"
  register: shfmt_release

# Had to see the format returned.
# JSON
# - debug: msg="{{ shfmt_release.tag }}"

- name: dev/shfmt - download
  become: true
  get_url:
    url: "https://github.com/mvdan/sh/releases/download/{{ shfmt_release.tag }}/shfmt_{{ shfmt_release.tag }}_linux_amd64"
    dest: /usr/local/bin/shfmt
    mode: "0755"
