---
all:
  children:
    desktops:
      hosts:
        poptop:
          ansible_host: poptop.local
          ansible_user: dustin
        tower:
          ansible_host: tower.local
          ansible_user: dustin
        donkeykong:
          ansible_host: donkeykong.local
          ansible_user: dustin
          ansible_connection: local

    laptops:
      hosts:
        sd-laptop:
          ansible_host: sd-laptop.local
          ansible_user: dustin
