---
# this file ensures baseline dependencies are met for the core of other tasks.
# i.e. tasks that install flatpaks would not work if flatpak was not installed
- name: dependencies - add canonical partners ppa
  become: yes
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu {{ ansible_distribution_release }} partner
    state: present
- name: dependencies - installing dependencies via apt
  become: yes
  ansible.builtin.apt:
    pkg:
      - python3-pip # install pip packages
      - flatpak # install flatpaks
      - gnome-software-plugin-flatpak
    state: present
- name: dependencies - installing dependencies via pip
  become: yes
  ansible.builtin.pip:
    name:
      - github3.py # for github latest releases
      - beautifulsoup4 # for web scraping

- name: dependencies - add the flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: dependencies - create ansible module folder
  file:
    path: "{{SYSTEM_HOME}}/.ansible/modules/"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

- name: dependencies - create autostart folder
  file:
    path: "{{SYSTEM_HOME}}/.config/autostart/"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

- name: dependencies - installing scrape.py andible module
  copy:
    src: ../files/home/.ansible/modules/scrape.py
    dest: "{{SYSTEM_HOME}}/.ansible/modules/scrape.py"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

- name: dependencies - create ansible automation folder
  file:
    path: "{{ SYSTEM_HOME }}/.config/ansible-automation"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
