- name: system/services - enable system services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop: "{{ SERVICES }}"
  when: SERVICES is defined

- name: system/services - fixing ubuntu .local name resolution
  become: true
  replace:
    path: /etc/nsswitch.conf
    regexp: "^hosts:(.*)files mdns.*"
    replace: "hosts:          files dns mdns4_minimal [NOTFOUND=return] myhostname"
