- name: system/ssh - installing openssh-server
  become: yes
  ansible.builtin.apt:
    pkg:
      - openssh-server
    state: present

- name: system/services - enable system services
  become: yes
  ansible.builtin.service:
    name: "ssh"
    enabled: yes
    state: restarted


- name: system/ssh - install gh ssh pub keys
  authorized_key:
    user: "{{ SYSTEM_USER }}"
    state: present
    key: "https://github.com/{{ item }}.keys"
  with_items:
    - "{{ MY_GITHUB_USERNAME }}"

# - name: system/ssh - fixing ssh priv key permissions
#   become: yes
#   file:
#     path: "{{ SYSTEM_HOME }}/.ssh/id_rsa"
#     owner: "{{ SYSTEM_USER }}"
#     group: "{{ SYSTEM_USER }}"
#     mode: 0600

# - name: system/ssh - fixing ssh pub key permissions
#   become: yes
#   file:
#     path: "{{ SYSTEM_HOME }}/.ssh/id_rsa.pub"
#     owner: "{{ SYSTEM_USER }}"
#     group: "{{ SYSTEM_USER }}"
#     mode: 0600
