- name: ufw.yaml - enable ufw
  become: yes
  community.general.ufw:
    state: enabled
- name: ufw.yaml - opening tcp ports
  become: yes
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ TCP_PORTS }}"
  when: TCP_PORTS is defined
- name: ufw.yaml - opening udp ports
  become: yes
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ UDP_PORTS }}"
  when: UDP_PORTS is defined
