- name: system/ufw - enable ufw
  become: true
  community.general.ufw:
    state: enabled
- name: system/ufw - opening tcp ports
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ TCP_PORTS }}"
  when: TCP_PORTS is defined
- name: system/ufw - opening udp ports
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ UDP_PORTS }}"
  when: UDP_PORTS is defined
