# - name: system/wallpaper - disable gnome flashback for peek
#   # become: yes
#   community.general.dconf:
#     key: "/org/gnome/gnome-flashback/screencast"
#     value: "false"
#     state: present

- name: system/wallpaper - set desktop background
  # become: yes
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "{{ WALLPAPER_PATH }}"
    state: present
  when: WALLPAPER_PATH is defined

- name: system/wallpaper - set screensaver background
  # become: yes
  community.general.dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "{{ WALLPAPER_PATH }}"
    state: present
  when: WALLPAPER_PATH is defined
