---
# tasks file for zsh
- name: system/zsh - installing shell
  become: yes
  ansible.builtin.apt:
    pkg:
      - git
      - zsh
      - fonts-powerline
      - powerline
      - direnv
      - zoxide
      - bat
      - exa
      - fd-find
    state: present
  register: install_zsh

- name: system/zsh - setup folders
  file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
  with_items:
    - "{{SYSTEM_HOME }}/.config/zsh"
    - "{{SYSTEM_HOME }}/.bookmarks"
    # - "{{SYSTEM_HOME }}/code"
    - "{{SYSTEM_HOME }}/tmp"

- name: system/zsh - change current user shell
  become: yes
  user:
    name: "{{ SYSTEM_USER }}"
    shell: /usr/bin/zsh

- name: system/zsh - placing .zshrc
  copy:
    src: ../files/home/.zshrc
    dest: "{{SYSTEM_HOME }}/.zshrc"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

- name: system/zsh - placing .zshenv
  copy:
    src: ../files/home/.zshenv
    dest: "{{SYSTEM_HOME }}/.zshenv"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

- name: system/zsh - placing .p10k.zsh cfg
  copy:
    src: ../files/home/.p10k.zsh
    dest: "{{SYSTEM_HOME }}/.p10k.zsh"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

# ####
- name: system/zsh - placing zsh function files
  ansible.posix.synchronize:
    src: ../files/home/.config/zsh/
    dest: "{{SYSTEM_HOME}}/.config/zsh"

# - name: system/zsh - create shell bookmark for code
#   ansible.builtin.file:
#     src: "{{SYSTEM_HOME }}/code"
#     dest: "{{SYSTEM_HOME }}/.bookmarks/@code"
#     owner: "{{ SYSTEM_USER }}"
#     group: "{{ SYSTEM_USER }}"
#     state: link
#     mode: "0700"

- name: system/zsh - create shell bookmark for tmp
  ansible.builtin.file:
    src: "{{SYSTEM_HOME }}/tmp"
    dest: "{{SYSTEM_HOME }}/.bookmarks/@tmp"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    state: link
    mode: "0700"

- name: system/zsh - create shell bookmark for Downloads
  ansible.builtin.file:
    src: "{{SYSTEM_HOME }}/Downloads"
    dest: "{{SYSTEM_HOME }}/.bookmarks/@Downloads"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    state: link
    mode: "0700"

- name: system/zsh - create shell bookmark for config
  ansible.builtin.file:
    src: "{{SYSTEM_HOME }}/.config"
    dest: "{{SYSTEM_HOME }}/.bookmarks/@config"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    state: link
    mode: "0700"

- name: system/zsh - batcat bat
  become: yes
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    owner: root
    group: root
    state: link
