---
# Terraform installation tasks for Ubuntu 24.04

# Installation tasks (when state is present)
- name: Add HashiCorp repository with GPG key
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: [deb]
    uris: https://apt.releases.hashicorp.com
    suites: "{{ ansible_distribution_release }}"
    components: [main]
    architectures: "{{ terraform_arch_mapping[ansible_architecture] | default(ansible_architecture) }}"
    signed_by: "{{ terraform_gpg_key_url }}"
    state: "{{ terraform_state }}"
  become: true

- name: Update apt cache after repository changes
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Terraform package
  ansible.builtin.apt:
    name: "{{ terraform_packages }}"
    state: "{{ terraform_state }}"
    purge: "{{ terraform_state == 'absent' }}"
  become: true
