---
# COSMIC theme color extraction
# Must run early so other roles can consume the generated color palette

- name: Install color extraction script
  ansible.builtin.copy:
    src: ../../../scripts/extract-cosmic-colors.sh
    dest: /usr/local/bin/extract-cosmic-colors
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Extract COSMIC theme colors for active mode (in-memory)
  ansible.builtin.shell: /usr/local/bin/extract-cosmic-colors
  register: theme_colors_json
  changed_when: false
  become: true
  become_user: "{{ user.name }}"

- name: Parse active theme colors as Ansible variable
  ansible.builtin.set_fact:
    theme_colors: "{{ theme_colors_json.stdout | from_json }}"

- name: Extract COSMIC Dark theme colors
  ansible.builtin.shell: /usr/local/bin/extract-cosmic-colors Dark
  register: theme_colors_dark_json
  changed_when: false
  become: true
  become_user: "{{ user.name }}"

- name: Parse Dark theme colors
  ansible.builtin.set_fact:
    theme_colors_dark: "{{ theme_colors_dark_json.stdout | from_json }}"

- name: Extract COSMIC Light theme colors
  ansible.builtin.shell: /usr/local/bin/extract-cosmic-colors Light
  register: theme_colors_light_json
  changed_when: false
  become: true
  become_user: "{{ user.name }}"

- name: Parse Light theme colors
  ansible.builtin.set_fact:
    theme_colors_light: "{{ theme_colors_light_json.stdout | from_json }}"
