---
# COSMIC theme color extraction
# Must run early so other roles can consume the generated color palette

- name: Install color extraction script
  ansible.builtin.copy:
    src: ../../../scripts/extract-cosmic-colors.sh
    dest: /usr/local/bin/extract-cosmic-colors
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Ensure user config directory exists
  ansible.builtin.file:
    path: "{{ user.home }}/.config"
    state: directory
    owner: "{{ user.name }}"
    mode: '0755'

- name: Extract COSMIC theme colors to JSON
  ansible.builtin.shell: /usr/local/bin/extract-cosmic-colors > {{ user.home }}/.config/theme-colors.json
  args:
    creates: "{{ user.home }}/.config/theme-colors.json"
  register: theme_extraction
  become: true
  become_user: "{{ user.name }}"

- name: Force theme color regeneration if COSMIC config changed
  ansible.builtin.shell: /usr/local/bin/extract-cosmic-colors > {{ user.home }}/.config/theme-colors.json
  when: theme_extraction.changed
  become: true
  become_user: "{{ user.name }}"

- name: Set permissions on theme colors file
  ansible.builtin.file:
    path: "{{ user.home }}/.config/theme-colors.json"
    owner: "{{ user.name }}"
    mode: '0644'

- name: Load theme colors as Ansible variable
  ansible.builtin.include_vars:
    file: "{{ user.home }}/.config/theme-colors.json"
    name: theme_colors
