---
- name: Configuring desktop system
  hosts: localhost
  become: false
  pre_tasks:
    - name: Set variables - include all .yaml files in config/shared directory
      ansible.builtin.include_vars:
        dir: ../config/shared
        extensions:
          - 'yaml'
    - name: Set variables - include all .yaml files in config/tower directory
      ansible.builtin.include_vars:
        dir: ../config/poptop
        extensions:
          - 'yaml'
    - name: Update apt cache
      become: true
      ansible.builtin.ansible.builtin.apt:
        update_cache: true

  tasks:
    - ansible.builtin.import_tasks: ../pkgs/dependencies.yaml
    - ansible.builtin.import_tasks: ../pkgs/ini.yaml
    - ansible.builtin.import_tasks: ../tasks/desktop/software/init.yaml
    - ansible.builtin.import_tasks: ../tasks/dev/init.yaml
    - ansible.builtin.import_tasks: ../tasks/cloud/init.yaml
    - ansible.builtin.import_tasks: ../tasks/system/init.yaml
    - ansible.builtin.import_tasks: ../tasks/desktop/software/tower-software.yaml
    - ansible.builtin.import_tasks: ../tasks/desktop/popos.yaml
  # roles:
    # - zsh
  post_tasks:
    - name: updating the system
      become: true
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
    - name: autoremove and purge apt packages
      become: true
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
    - ansible.builtin.import_tasks: ../tasks/final-message.yaml