---
# Node.js installation from NodeSource official repository

- name: Add NodeSource repository with GPG key
  ansible.builtin.deb822_repository:
    name: nodesource
    types: [deb]
    uris: https://deb.nodesource.com/node_{{ nodejs_version }}.x
    suites: nodistro
    components: [main]
    signed_by: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: "{{ nodejs_state }}"
  become: true

- name: Update APT cache after repository changes
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Node.js and npm
  ansible.builtin.apt:
    name: nodejs
    state: "{{ nodejs_state }}"
    purge: "{{ nodejs_state == 'absent' }}"
  become: true
