---
# Node.js installation from NodeSource official repository

- name: Install dependencies for Node.js
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  become: yes
  when: nodejs_state == 'present'

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes
  when: nodejs_state == 'present'

- name: Download NodeSource GPG key
  get_url:
    url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    dest: /tmp/nodesource.asc
    mode: '0644'
  become: yes
  when: nodejs_state == 'present'

- name: Add NodeSource GPG key
  shell: |
    gpg --dearmor < /tmp/nodesource.asc > /etc/apt/keyrings/nodesource.gpg
    chmod 644 /etc/apt/keyrings/nodesource.gpg
  args:
    creates: /etc/apt/keyrings/nodesource.gpg
  become: yes
  when: nodejs_state == 'present'

- name: Clean up temporary GPG key file
  file:
    path: /tmp/nodesource.asc
    state: absent
  become: yes
  when: nodejs_state == 'present'

- name: Add NodeSource repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main"
    filename: nodesource
    state: present
  become: yes
  when: nodejs_state == 'present'

- name: Install Node.js and npm
  apt:
    name: nodejs
    state: "{{ nodejs_state }}"
    update_cache: yes
  become: yes

# Cleanup when absent
- name: Remove NodeSource repository when absent
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main"
    filename: nodesource
    state: absent
  become: yes
  when: nodejs_state == 'absent'

- name: Remove NodeSource GPG key when absent
  file:
    path: /etc/apt/keyrings/nodesource.gpg
    state: absent
  become: yes
  when: nodejs_state == 'absent'

- name: Remove Node.js package when absent
  apt:
    name: nodejs
    state: absent
  become: yes
  when: nodejs_state == 'absent'
