---
# Git installation and configuration

- name: Install git (from core_packages)
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Install git-related tools
  ansible.builtin.apt:
    name:
      - git-lfs
      - gitk
      - git-gui
      - git-delta
    state: present
  become: true

- name: Install difftastic from GitHub
  ansible.builtin.include_tasks: ../../tasks/includes/github_release.yml
  vars:
    org: Wilfred
    repo: difftastic
    binary_name: difft
    filename_substring: x86_64-unknown-linux-gnu.tar.gz
  when: git_difftastic.enable | default(false)

- name: Install lazygit from GitHub
  ansible.builtin.include_tasks: ../../tasks/includes/github_release.yml
  vars:
    org: jesseduffield
    repo: lazygit
    binary_name: lazygit
    filename_substring: linux_x86_64.tar.gz

- name: Remove old GitHub CLI repository configuration (if exists)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/github-cli.list
    state: absent
  become: true

- name: Add GitHub CLI repository with GPG key
  ansible.builtin.deb822_repository:
    name: github-cli
    types: [deb]
    uris: https://cli.github.com/packages
    suites: stable
    components: [main]
    architectures: "{{ gh_arch_mapping[ansible_architecture] | default(ansible_architecture) }}"
    signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present
  become: true

- name: Update APT cache after repository changes
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install GitHub CLI
  ansible.builtin.apt:
    name: gh
    state: present
  become: true

- name: Create git config directory
  ansible.builtin.file:
    path: "{{ user.home }}/.config/git"
    state: directory
    owner: "{{ user.name }}"
    mode: '0755'

- name: Deploy gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ user.home }}/.gitconfig"
    owner: "{{ user.name }}"
    mode: '0644'

- name: Deploy git allowed_signers for SSH signing
  ansible.builtin.template:
    src: git-allowed_signers.j2
    dest: "{{ user.home }}/.config/git/allowed_signers"
    owner: "{{ user.name }}"
    mode: '0644'

- name: Create gh config directory
  ansible.builtin.file:
    path: "{{ user.home }}/.config/gh"
    state: directory
    owner: "{{ user.name }}"
    mode: '0755'

- name: Deploy gh (GitHub CLI) config
  ansible.builtin.template:
    src: gh-config.yml.j2
    dest: "{{ user.home }}/.config/gh/config.yml"
    owner: "{{ user.name }}"
    mode: '0644'

- name: Create lazygit config directory
  ansible.builtin.file:
    path: "{{ user.home }}/.config/lazygit"
    state: directory
    owner: "{{ user.name }}"
    mode: '0755'

- name: Deploy lazygit config
  ansible.builtin.template:
    src: lazygit-config.yml.j2
    dest: "{{ user.home }}/.config/lazygit/config.yml"
    owner: "{{ user.name }}"
    mode: '0644'
