- name: cloud/doppler - download doppler gpg key file
  become: yes
  get_url:
    url: https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key
    dest: /etc/apt/trusted.gpg.d/doppler_gpg.asc
    mode: '0644'
    force: true

- name: cloud/doppler - add  apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/doppler_gpg.asc] https://packages.doppler.com/public/cli/deb/debian any-version main"
    state: present
    filename: doppler
    update_cache: true

- name: cloud/doppler - install dependencies
  become: yes
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: cloud/doppler - install
  become: yes
  ansible.builtin.apt:
    pkg:
      - doppler
    state: present
