- name: cloud/doppler - add signing keys
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key
    state: present

- name: cloud/doppler - add  apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://packages.doppler.com/public/cli/deb/debian any-version main"
    state: present
    filename: doppler
    update_cache: true

- name: cloud/doppler - install dependencies
  become: yes
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: cloud/doppler - install
  become: yes
  ansible.builtin.apt:
    pkg:
      - doppler
    state: present
