- name: cloud/k3sup - get latest release version of k3sup from github
  github_release:
    user: alexellis
    repo: k3sup
    action: latest_release
    token: "{{ GITHUB_TOKEN }}"
  register: k3sup_release

- name: cloud/k3sup - clean up k3sup version number
  set_fact:
    k3sup_version: "{{ k3sup_release.tag | regex_replace('^v', '') }}"

- name: cloud/k3sup - Download and install k3sup from github
  become: yes
  get_url:
    url: https://github.com/alexellis/k3sup/releases/download/{{ k3sup_version }}/k3sup
    dest: /usr/local/bin/k3sup
    mode: "0755"