---
# oq installation
# Performant jq alternative for querying JSON, YAML, XML, and more
# https://github.com/plutov/oq

- name: Install oq from GitHub
  ansible.builtin.include_tasks: ../../system/tasks/includes/github_release.yml
  vars:
    org: plutov
    repo: oq
    binary_name: oq
    version: latest
    filename_substring: linux_amd64.tar.gz
  when: app_states['oq'] | default('present') == 'present'

- name: Remove oq binary when absent
  file:
    path: /usr/local/bin/oq
    state: absent
  when: app_states['oq'] | default('present') == 'absent'
  become: yes
