- name: system/software/draw.io - get latest release version
  github_release:
    user: jgraph
    repo: drawio-desktop
    action: latest_release
    token: "{{ GITHUB_TOKEN }}"
  register: drawio_release

- name: system/software/draw.io - get drawio version number w/o v
  set_fact:
    drawio_version: "{{ drawio_release.tag | regex_replace('^v', '') }}"

- name: system/software/draw.io - install
  become: yes
  apt:
    deb: https://github.com/jgraph/drawio-desktop/releases/download/{{ drawio_release.tag }}/drawio-amd64-{{ drawio_version }}.deb