---
# Docker installation state (present or absent)
docker_state: present

# Docker packages to install
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Conflicting packages to remove before installation
docker_conflicting_packages:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc

# Docker GPG key URL
docker_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg

# Architecture mapping (Ansible fact -> Debian/Ubuntu architecture)
docker_arch_mapping:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf

# Add user to docker group (allows running docker without sudo)
docker_add_user_to_group: true
