- name: dev/elementary-sdk - install elementary sdk
  become: true
  ansible.builtin.apt:
    pkg:
      - build-essential
      - desktop-file-utils
      - debconf-utils
      - debhelper
      - ubuntu-dev-tools
      - piuparts
      - schroot
      - sbuild
      - software-properties-common
      - dh-make
    state: present

- name: dev/ubuntu-packaging - placing .sbuildrc
  copy:
    src: files/home/.sbuildrc
    dest: "{{ SYSTEM_HOME }}/.sbuildrc"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    mode: 0700

- name: dev/ubuntu-packaging - placing .mk-sbuild.rc
  copy:
    src: files/home/.mk-sbuild.rc
    dest: "{{ SYSTEM_HOME }}/.mk-sbuild.rc"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    mode: 0700

- name: dev/ubuntu-packaging - placing .quiltrc
  copy:
    src: files/home/.quiltrc
    dest: "{{ SYSTEM_HOME }}/.quiltrc"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"
    mode: 0700
