- name: desktop/software/appimage-launcher - installing software-properties-common
  become: yes
  ansible.builtin.apt:
    pkg:
      - software-properties-common
    state: present

- name: desktop/software/appimage-launcher- add repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "ppa:appimagelauncher-team/stable"
    state: present
    filename: appimagelauncher
    update_cache: true

- name: desktop/software/appimage-launcher - installing appimagelauncher
  become: yes
  ansible.builtin.apt:
    pkg:
      - appimagelauncher
    state: present
