---
# tasks file for chrome-browser
- name: desktop/software/chrome-browser - set apt gpg key
  become: yes
  ansible.builtin.apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present

- name: desktop/software/chrome-browser - add repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome
    update_cache: true

- name: desktop/software/chrome-browser - install
  become: yes
  ansible.builtin.apt:
    name: google-chrome-stable
