- name: desktop/software/common-software - installing flatpaks
  community.general.flatpak:
    name:
      - md.obsidian.Obsidian
      - com.todoist.Todoist
      - org.telegram.desktop
      - com.obsproject.Studio
    state: present
    method: user
    remote: flathub

- name: desktop/software/common-software - installing debs
  become: yes
  ansible.builtin.apt:
    pkg:
      - dconf-cli
      - xournal
      - restic
      - xclip
      - ncdu
      - ubuntu-restricted-extras
      - ubuntu-restricted-addons
      - gnome-disk-utility
      - gnome-firmware
      - dlocate
      - ttf-mscorefonts-installer
      - fonts-powerline
      - fonts-emojione
      - ppa-purge
      - gnome-calculator
      - dialog
      - stacer
      - gnupg-agent
      - font-manager
      - v4l-utils
      - nvme-cli
      - celluloid
      - zoxide
      - jq
      - whois
      - curl
      - wget
      - tmux
      # cargo dependency
      - pkg-config
    state: present

- name: desktop/software/common-software - removing debs
  become: yes
  ansible.builtin.apt:
    pkg:
      - firefox
    state: absent

- name: desktop/software/common-software - install pip packages
  pip:
    name:
      - ansible-lint
      - telegram-send
      # Needed for some ansible modules
      - psutil

- name: dependencies - create Applications folder
  file:
    path: "{{ SYSTEM_HOME }}/Applications"
    state: directory
    mode: "0700"
    owner: "{{ SYSTEM_USER }}"
    group: "{{ SYSTEM_USER }}"

# - name: desktop/software/common-software - adding todoist
#   copy:
#     src: ../files/home/Applications/Todoist.AppImage
#     dest: "{{ SYSTEM_HOME }}/Applications/Todoist.AppImage"
#     owner: "{{ SYSTEM_USER }}"
#     group: "{{ SYSTEM_USER }}"
#     mode: 0644