- name: desktop/software/element - add element's public pgp key to the apt keyring
  become: yes
  ansible.builtin.apt_key:
    url: "https://packages.element.io/debian/element-io-archive-keyring.gpg"

- name: desktop/software/element - add element's stable apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://packages.element.io/debian/ default main"
    state: present
    filename: element-io
    update_cache: true

- name: desktop/software/element - install element's  dependencies
  become: yes
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
    state: present

- name: desktop/software/element - install element
  become: yes
  ansible.builtin.apt:
    pkg:
      - element-desktop
    state: present
