- name: desktop/software/screenshot - installing
  become: true
  ansible.builtin.apt:
    pkg:
      - flameshot
    state: present

- name: desktop/software/screenshot - disable gnome flashback
  become: true
  become_user: "{{ SYSTEM_USER }}"
  community.general.dconf:
    key: "/org/gnome/gnome-flashback/screenshot"
    value: "false"
    state: present

- name: desktop/software/screenshot - disable old screenshot shortcut
  become: true
  become_user: "{{ SYSTEM_USER }}"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screenshot"
    # value: "['<Primary><Alt><Super>Calculator']"
    value: "['']"
    state: present

# Next four are all needed to create the custom shortcut
- name: desktop/software/screenshot - set custom print binding
  become: true
  become_user: "{{ SYSTEM_USER }}"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Shift><Super>s'"
    state: present
- name: desktop/software/screenshot - set print binding to flameshot command
  become: true
  become_user: "{{ SYSTEM_USER }}"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'flameshot gui'"
    state: present
- name: desktop/software/screenshot - set flameshot shortcut name
  become: true
  become_user: "{{ SYSTEM_USER }}"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'Flameshot'"
    state: present
- name: desktop/software/screenshot - set flameshot shortcut custom binding
  become: true
  become_user: "{{ SYSTEM_USER }}"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    state: present
