- name: desktop/software/sd - get latest release version
  github_release:
    user: chmln
    repo: sd
    action: latest_release
    token: "{{ GITHUB_TOKEN }}"
  register: sd_release

- name: desktop/software/sd - get sd version number w/o v
  set_fact:
    sd_version: "{{ sd_release.tag | regex_replace('^v', '') }}"

- name: desktop/software/sd - install
  become: yes
  ansible.builtin.get_url:
    url: https://github.com/chmln/sd/releases/download/{{ sd_release.tag }}/sd-{{ sd_release.tag }}-x86_64-unknown-linux-gnu
    dest: /usr/local/bin/sd
    mode: '0755'