---
- name: desktop/software/slack - download slack gpg key file
  become: true
  get_url:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    dest: /etc/apt/trusted.gpg.d/slack_gpg.asc
    mode: "0644"
    force: true

- name: desktop/software/slack - add repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/slack_gpg.asc] https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"
    state: present
    filename: slack
    update_cache: true

- name: desktop/software/slack - install
  become: true
  ansible.builtin.apt:
    name: slack-desktop
