---
- name: desktop/software/slack - download slack gpg key file
  get_url:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    dest: /etc/apt/trusted.gpg.d/slack_gpg.gpg
    mode: '0644'
    force: true

- name: desktop/software/slack - add repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"
    state: present
    filename: slack
    update_cache: true

- name: desktop/software/slack - install
  become: yes
  ansible.builtin.apt:
    name: slack-desktop
