- name: desktop/software/starship - get latest release version of starship from github
  github_release:
    user: starship
    repo: starship
    action: latest_release
    token: "{{ GITHUB_TOKEN }}"
  register: starship_release

# Had to see the format returned.
# JSON
# - debug: msg="{{ starship_release.tag }}"

- name: desktop/software/starship - download & extract starship tgz
  become: yes
  ansible.builtin.unarchive:
    src: "https://github.com/starship/starship/releases/download/{{ starship_release.tag }}/starship-x86_64-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    remote_src: yes