- name: desktop/software/tailscale - download tailscale gpg key file
  become: true
  get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg
    dest: /etc/apt/trusted.gpg.d/tailscale.asc
    mode: "0644"
    force: true

- name: desktop/software/tailscale - add tailiscale stable repository for previous release
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/tailscale.asc] https://pkgs.tailscale.com/stable/ubuntu {{ TAILSCALE_UBUNTU_VERSION }} main"
    update_cache: true
  when: TAILSCALE_UBUNTU_VERSION is defined

- name: desktop/software/tailscale - add tailiscale stable repository for the latest release
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/tailscale.asc] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: tailscale
    update_cache: true
  when: TAILSCALE_UBUNTU_VERSION is undefined

- name: desktop/software/tailscale - install tailiscale vpn
  become: true
  ansible.builtin.apt:
    name: tailscale
    update_cache: true
