---
- name: Install Brave web app "asana" launcher
  ansible.builtin.copy:
    src: "brave-asana-launcher.sh"
    dest: "/usr/local/bin/brave-asana"
    mode: "0755"
    owner: root
    group: root
  become: true
  when: app_states['asana'] | default('present') == 'present'

- name: Install Brave web app "asana" desktop entry
  ansible.builtin.copy:
    src: "brave-asana.desktop"
    dest: "/usr/share/applications/brave-asana.desktop"
    mode: "0644"
    owner: root
    group: root
  become: true
  when: app_states['asana'] | default('present') == 'present'

- name: Install Brave web app icons
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: "0644"
    owner: root
    group: root
  loop:
    - { src: "brave-asana-icon-16.png", dest: "/usr/share/icons/hicolor/16x16/apps/brave-asana.png" }
    - { src: "brave-asana-icon-32.png", dest: "/usr/share/icons/hicolor/32x32/apps/brave-asana.png" }
    - { src: "brave-asana-icon-48.png", dest: "/usr/share/icons/hicolor/48x48/apps/brave-asana.png" }
    - { src: "brave-asana-icon-64.png", dest: "/usr/share/icons/hicolor/64x64/apps/brave-asana.png" }
    - { src: "brave-asana-icon-128.png", dest: "/usr/share/icons/hicolor/128x128/apps/brave-asana.png" }
    - { src: "brave-asana-icon-256.png", dest: "/usr/share/icons/hicolor/256x256/apps/brave-asana.png" }
    - { src: "brave-asana-icon-512.png", dest: "/usr/share/icons/hicolor/512x512/apps/brave-asana.png" }
    - { src: "brave-asana-icon-800.png", dest: "/usr/share/icons/hicolor/scalable/apps/brave-asana.png" }
  become: true
  when: app_states['asana'] | default('present') == 'present'
  notify: Update icon cache

- name: Remove Brave web app launcher when absent
  ansible.builtin.file:
    path: "/usr/local/bin/brave-asana"
    state: absent
  become: true
  when: app_states['asana'] | default('present') == 'absent'

- name: Remove Brave web app desktop entry when absent
  ansible.builtin.file:
    path: "/usr/share/applications/brave-asana.desktop"
    state: absent
  become: true
  when: app_states['asana'] | default('present') == 'absent'

- name: Remove Brave web app icons when absent
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
    owner: root
    group: root
  loop:
    - /usr/share/icons/hicolor/16x16/apps/brave-asana.png
    - /usr/share/icons/hicolor/32x32/apps/brave-asana.png
    - /usr/share/icons/hicolor/48x48/apps/brave-asana.png
    - /usr/share/icons/hicolor/64x64/apps/brave-asana.png
    - /usr/share/icons/hicolor/128x128/apps/brave-asana.png
    - /usr/share/icons/hicolor/256x256/apps/brave-asana.png
    - /usr/share/icons/hicolor/512x512/apps/brave-asana.png
    - /usr/share/icons/hicolor/scalable/apps/brave-asana.png
  become: true
  when: app_states['asana'] | default('present') == 'absent'

