---
# Maintenance playbook - updates, cleanup, etc.
- name: System Maintenance
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: updates.auto_update | default(false)

    - name: Update flatpak packages
      command: flatpak update -y
      changed_when: false
      failed_when: false

    - name: Update snap packages
      command: snap refresh
      changed_when: false
      failed_when: false

    - name: Clean up old kernels
      shell: |
        apt autoremove --purge -y
      changed_when: false

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        msg: "Rebooting to apply updates"
        reboot_timeout: 300
      when:
        - reboot_required.stat.exists
        - updates.auto_reboot | default(false)
