---
- name: configuring desktop system
  hosts: localhost
  become: no
  pre_tasks:
    - name: set variables - include all .yaml files in config/shared directory
      include_vars:
        dir: ../config/shared
        extensions:
          - 'yaml'
    - name: set variables - include all .yaml files in config/tower directory
      include_vars:
        dir: ../config/sd-laptop
        extensions:
          - 'yaml'
    - name: update repositories
      become: yes
      apt: update_cache=yes
      changed_when: false
    - import_tasks: ../tasks/dependencies.yaml
  tasks:
    - import_tasks: ../tasks/desktop/regolith.yaml
    - import_tasks: ../tasks/desktop/software/init.yaml
    - import_tasks: ../tasks/dev/init.yaml
    - import_tasks: ../tasks/cloud/init.yaml
    - import_tasks: ../tasks/system/init.yaml
    - name: install laptop specific software
      become: yes
      ansible.builtin.apt:
        pkg:
          - i3xrocks-battery
        state: present
  # roles:
    # - zsh
  post_tasks:
    - name: updating the system
      become: yes
      apt:
        update_cache: yes
        upgrade: dist
    - name: autoremove and purge apt packages
      become: yes
      apt:
        autoremove: yes
        purge: yes
