---
- name: configuring desktop system
  hosts: localhost
  become: no
  pre_tasks:
    - name: set variables - include all .yaml files in config/shared directory
      include_vars:
        dir: ../config/shared
        extensions:
          - 'yaml'
    - name: set variables - include all .yaml files in config/tower directory
      include_vars:
        dir: ../config/tower
        extensions:
          - 'yaml'
    - name: update repositories
      become: yes
      apt: update_cache=yes
      changed_when: false
    - import_tasks: ../tasks/task-dependencies.yaml
  tasks:
    - import_tasks: ../tasks/system/nala.yaml
    - import_tasks: ../tasks/system/software/edge-browser.yaml
    - import_tasks: ../tasks/dev/code-insiders.yaml
    - import_tasks: ../tasks/system/services.yaml
    - import_tasks: ../tasks/system/ufw.yaml
    - import_tasks: ../tasks/system/symlink.yaml
    - import_tasks: ../tasks/dev/git-config.yaml
    - import_tasks: ../tasks/dev/editor.yaml
    - import_tasks: ../tasks/desktops/regolith.yaml
    - import_tasks: ../tasks/system/ssh.yaml
    - import_tasks: ../tasks/system/sudo.yaml
    - import_tasks: ../tasks/system/sysctl.yaml
    - import_tasks: ../tasks/system/timezone.yaml
    - import_tasks: ../tasks/system/home.yaml
    - import_tasks: ../tasks/system/software/common-software.yaml
    - import_tasks: ../tasks/cloud/cloud-install.yaml
    - import_tasks: ../tasks/system/zsh.yaml
    - import_tasks: ../tasks/system/software/zoom.yaml
    - import_tasks: ../tasks/system/software/ncspot.yaml
  # roles:
    # - zsh
    # - ncspot
    # - code-insiders
    # - chrome-browser
    # - nala
    # - slack
    # - regolith
  post_tasks:
    - name: updating the system
      become: yes
      apt:
        update_cache: yes
        upgrade: dist
    - name: autoremove and purge apt packages
      become: yes
      apt:
        autoremove: yes
        purge: yes
